name: Build VM Image

on: [push]

jobs:
  build-image:
    runs-on: ubuntu-18.04
    name: packer

    steps:
      - name: Install VirtualBox
        run: sudo echo "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib" >> /etc/apt/sources.list && \
          wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add - && \
          sudo apt-get update && \
          sudo apt-get install virtualbox-6.1

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: playground.json

      - name: Build Artifact
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: playground.json
